### ISSUE TITLE
Separator

### ISSUE THREAD

**Issue by tlygnersjo** [justintadlock/hybrid-breadcrumbs#1]
This implementation of breadcrumbs looks awesome!

I just saw one thing that i think should be different and thats separators. Is it possible to add a parameter value so that it can be outputted (i.e. `<span class="separator">/</span>`) instead of a :after in css?

**Comment by justintadlock** [comment]
Separators are stylistic and should be output with CSS.  That's going to be a hard no on a separator argument.

You can always roll your own HTML though like:

```php
$crumbs = Trail::all( $args );

foreach ( $crumbs as $crumb ) {
	// Output items.
}
```

Public methods for `$crumb`: https://github.com/justintadlock/hybrid-breadcrumbs/blob/master/src/Contracts/Crumb.php

**Comment by tlygnersjo** [comment]
Thanks! You're probably right.

Thats a great workaround for use cases when we'll need to output a separator between each crumb.
