### ISSUE TITLE
WooCommerce trail bug (shop page)

### ISSUE THREAD

**Issue by tlygnersjo** [justintadlock/hybrid-breadcrumbs#2]
I think there is a bug when using WooCommerce and setting shop page to something else than front page (i have "https://domain.tld/products" as shop page).

I get a breadcrumb looking like this when browsing to shop page:
`Home > Products > Products
`

Instead it should be:
`Home > Products`

This is also the case on single product page (Home > Products > Products > Product name). This translates to the page https://domain.tld/products/product-name

Is this something that can be resolved?

Is it possible to hide the title "Browse:" in a breadcrumb?

**Comment by tlygnersjo** [comment]
@justintadlock Can you please have a look at this?

**Comment by justintadlock** [comment]
This is probably because WC is doing something non-standard.  My best guess is that you have something like a product CPT archive and a products page.

I'll take a look into it soon.

**Comment by justintadlock** [comment]
You can probably tell by looking at the classes generated on the individual breadcrumb items.  You should see classes for each item like `breadcrumbs__crumb--{$type}`.

**Comment by tlygnersjo** [comment]
Here's the output:
```
<nav class="breadcrumbs" role="navigation" aria-label="Breadcrumbs" itemprop="breadcrumb">
  <ul class="breadcrumbs__trail" itemscope="" itemtype="https://schema.org/BreadcrumbList">
    <li class="breadcrumbs__crumb breadcrumbs__crumb--home" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
      <a href="https://domain.tld/" itemprop="item">
        <span itemprop="name">Home</span>
      </a>
    </li>

    <li class="breadcrumbs__crumb breadcrumbs__crumb--post" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
      <a href="https://domain.tld/products" itemprop="item">
        <span itemprop="name">Products</span>
      </a>
    </li>

    <li class="breadcrumbs__crumb breadcrumbs__crumb--post-type" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
      <span itemprop="item">
        <span itemprop="name">Products</span>
      </span>
    </li>
  </ul>
</nav>
```

**Comment by tlygnersjo** [comment]
As said before "Products" (https://domain.tld/products) is set as "shop" page in WooCommerce settings. I don't have any CPT on this website.

**Comment by justintadlock** [comment]
Yep, as I suspected (based on the HTML output), you have both a `products` page and a CPT archive of `products`.  This is simply WC not following standards, which is not surprising.  I'll look into building a general purpose solution that would recognize when plugins do this as I'd rather not code something specific to a single third-party plugin.

> I don't have any CPT on this website.

WC itself creates the CPT.

**Comment by tlygnersjo** [comment]
Sounds great. That would be awesome! 💯

**Comment by tlygnersjo** [comment]
Do you know if there any temporary workaround until you've got this sorted out?

**Comment by tlygnersjo** [comment]
It would be great to have an solution to this, i'm about to go live with one website but this is limiting me to do this.

**Comment by tlygnersjo** [comment]
Would it also be possible to add a parameter like `'container' => false` in order to not output the container wrapper? This is for the render function (Hybrid\Breadcrumbs\Trail::render). Sometimes i want to create the container in a template rather than generate it?

**Comment by tlygnersjo** [comment]
Sorry to nag you about this! Any workaround for this? @justintadlock

**Comment by justintadlock** [comment]
I haven't had a chance to look into it yet.

I'm not that familiar with WC, but I wonder if you can delete their "products" page and simply use the standard CPT archive (products archive)?  Or, overwrite their CPT registration `$args` and set `has_archive` to `false`?  I'm not sure what either of those things would do.
