### ISSUE TITLE
Rich data test fails

### ISSUE THREAD

**Issue by rollecode** [justintadlock/hybrid-breadcrumbs#7]
With [Rich Results Tests](https://search.google.com/test/rich-results) we get failed results and also SEO tools like SEMrush report "Invalid structured data items". Any way to fix this?

![Screen-Shot-2020-12-14-08-23-23 11](https://user-images.githubusercontent.com/1534150/102047366-cfeaaa80-3de5-11eb-87d8-257a3df93dca.png)

**Comment by samikeijonen** [comment]
Related to #5?

**Comment by rollecode** [comment]
Went through the issues but didn't realize there's a pull request. Indeed, @samikeijonen. Closing this for now, hoping that PR gets approved.
